name: Build and Deploy PySpark Project to Databricks

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Build wheel file
        run: python setup.py bdist_wheel

      - name: Upload wheel to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          WHL_PATH=$(ls dist/*.whl)
          databricks fs cp $WHL_PATH dbfs:/FileStore/wheels/ --overwrite

      - name: Deploy Databricks Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks jobs create --json-file databricks_job.json || \
          (echo "Job exists, updating..." && databricks jobs reset --job-id $(databricks jobs list | grep PySpark_ETL_Job | awk '{print $1}') --json-file databricks_job.json)
